#!/usr/bin/env bash

DEPENDENCIES=(node)
SCRIPT_NAME=$(basename "$0")
VERSION="1.1.0"

DEPLOY_DIR="__DEPLOY_DIR__"
LOG_DIR="$DEPLOY_DIR/logs"
PID_DIR="$DEPLOY_DIR/pids"
ENV_FILE="$DEPLOY_DIR/.env.production"
HTTPS_CONFIG="$DEPLOY_DIR/.https-config"

# HTTPS mode detection
HTTPS_ENABLED=false

function usage() {
    cat <<EOM

Planny-Flows Production Startup Script
This file is generated by setup.sh from templates/start.sh

usage: ${SCRIPT_NAME} [options]

options:
    -h|--help             Show this help message
    --version             Show version information

dependencies: ${DEPENDENCIES[*]}

EOM
    exit 1
}

function exit_on_missing_tools() {
    for cmd in "$@"; do
        if command -v "$cmd" &>/dev/null; then
            continue
        fi
        printf "Error: Required tool '%s' is not installed or not in PATH\n" "$cmd"
        exit 1
    done
}

function log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >&2
}

function check_https_config() {
    if [[ -f "$HTTPS_CONFIG" ]]; then
        # Source the HTTPS config
        # shellcheck source=/dev/null
        source "$HTTPS_CONFIG" 2>/dev/null || true
        
        if [[ "${HTTPS_ENABLED:-false}" == "true" ]]; then
            HTTPS_ENABLED=true
        fi
    fi
}



function cleanup() {
    log "Shutting down..."
    [ -f "$PID_DIR/api.pid" ] && kill "$(cat "$PID_DIR/api.pid")" 2>/dev/null || true
    [ -f "$PID_DIR/client.pid" ] && kill "$(cat "$PID_DIR/client.pid")" 2>/dev/null || true
    rm -f "$PID_DIR"/*.pid 2>/dev/null || true
    exit 0
}

function load_environment() {
    if [ -f "$ENV_FILE" ]; then
        while IFS= read -r line || [ -n "$line" ]; do
            case "$line" in
            \#* | "") continue ;;
            *) export "$line" ;;
            esac
        done < "$ENV_FILE"
    fi
}

function start_api() {
    log "Starting API..."

    cd "$DEPLOY_DIR/api" || {
        log "ERROR: Failed to change to API directory"
        exit 1
    }

    NODE_ENV=production node -r ./tsconfig-paths.js build/index.js >> "$LOG_DIR/api.log" 2>> "$LOG_DIR/api-error.log" &
    local api_pid=$!
    echo "$api_pid" > "$PID_DIR/api.pid"

    sleep 2

    if ! kill -0 "$api_pid" 2>/dev/null; then
        log "ERROR: API failed to start"
        exit 1
    fi

    log "API started (PID: $api_pid)"
    echo "$api_pid"
}

function start_client() {
    log "Starting Client..."

    cd "$DEPLOY_DIR/client" || {
        log "ERROR: Failed to change to client directory"
        exit 1
    }

    PORT=8193 node server.js >> "$LOG_DIR/client.log" 2>> "$LOG_DIR/client-error.log" &
    local client_pid=$!
    echo "$client_pid" > "$PID_DIR/client.pid"

    sleep 1

    if ! kill -0 "$client_pid" 2>/dev/null; then
        log "ERROR: Client failed to start"
        return 1
    fi

    log "Client started (PID: $client_pid)"
    echo "$client_pid"
}

function monitor_processes() {
    local api_pid="$1"
    local client_pid="$2"

    while true; do
        if ! kill -0 "$api_pid" 2>/dev/null; then
            log "API died"
            exit 1
        fi
        if ! kill -0 "$client_pid" 2>/dev/null; then
            log "Client died"
            exit 1
        fi
        sleep 5
    done
}

function main() {
    while [ "$1" != "" ]; do
        case $1 in
        --version)
            echo "${SCRIPT_NAME} version ${VERSION}"
            exit 0
            ;;
        -h | --help)
            usage
            ;;
        *)
            echo "Error: Unknown option '$1'" >&2
            usage
            ;;
        esac
        shift
    done

    exit_on_missing_tools "${DEPENDENCIES[@]}"

    mkdir -p "$LOG_DIR" "$PID_DIR" || {
        log "ERROR: Failed to create directories"
        exit 1
    }

    # Check HTTPS configuration
    check_https_config

    trap cleanup SIGTERM SIGINT

    load_environment

    log "Starting Planny-Flows..."

    local api_pid
    api_pid=$(start_api)

    local client_pid
    client_pid=$(start_client) || {
        kill "$api_pid" 2>/dev/null || true
        exit 1
    }

    # Determine display URL
    local display_url
    if [[ "$HTTPS_ENABLED" == true ]]; then
        if [[ -n "${TAILSCALE_IP:-}" ]]; then
            display_url="https://${TAILSCALE_IP}"
        else
            display_url="https://__HOSTNAME__.local"
        fi
    else
        display_url="http://__HOSTNAME__.local:8193"
    fi

    log "Planny-Flows running at $display_url"
    if [[ "$HTTPS_ENABLED" == true ]]; then
        log "API available at: $display_url/api"
    else
        log "API available at: http://__HOSTNAME__.local:3824"
    fi

    monitor_processes "$api_pid" "$client_pid"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
    exit 0
fi
