#!/bin/bash
# Planny-Flows Production Startup Script
# This file is generated by setup.sh from templates/start.sh

set -e

PROJECT_DIR="__PROJECT_DIR__"
DEPLOY_DIR="__DEPLOY_DIR__"
LOG_DIR="__DEPLOY_DIR__/logs"
PID_DIR="__DEPLOY_DIR__/pids"
ENV_FILE="__DEPLOY_DIR__/.env.production"

mkdir -p "$LOG_DIR" "$PID_DIR"

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

cleanup() {
  log "Shutting down..."
  [ -f "$PID_DIR/api.pid" ] && kill $(cat "$PID_DIR/api.pid") 2>/dev/null || true
  [ -f "$PID_DIR/client.pid" ] && kill $(cat "$PID_DIR/client.pid") 2>/dev/null || true
  rm -f "$PID_DIR"/*.pid 2>/dev/null || true
  exit 0
}

trap cleanup SIGTERM SIGINT

# Load environment (includes JWT_SECRET)
if [ -f "$ENV_FILE" ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      \#*|"") continue ;;
      *) export "$line" ;;
    esac
  done < "$ENV_FILE"
fi

log "Starting Planny-Flows..."

# Start API
cd "$PROJECT_DIR/api"
nohup node -r ./tsconfig-paths.js build/index.js >> "$LOG_DIR/api.log" 2>> "$LOG_DIR/api-error.log" &
echo $! > "$PID_DIR/api.pid"
API_PID=$!
sleep 2

if ! kill -0 $API_PID 2>/dev/null; then
  log "ERROR: API failed to start"
  exit 1
fi
log "API started (PID: $API_PID)"

# Start Client (explicit PORT to avoid conflict)
cd "$PROJECT_DIR/client"
PORT=8081 nohup node server.js >> "$LOG_DIR/client.log" 2>> "$LOG_DIR/client-error.log" &
echo $! > "$PID_DIR/client.pid"
CLIENT_PID=$!
sleep 1

if ! kill -0 $CLIENT_PID 2>/dev/null; then
  log "ERROR: Client failed to start"
  kill $API_PID 2>/dev/null || true
  exit 1
fi
log "Client started (PID: $CLIENT_PID)"
log "Planny-Flows running at http://__HOSTNAME__.local:8081"

# Monitor processes
while true; do
  kill -0 $API_PID 2>/dev/null || { log "API died"; exit 1; }
  kill -0 $CLIENT_PID 2>/dev/null || { log "Client died"; exit 1; }
  sleep 5
done
