#!/usr/bin/env bash
#
# setup-https.sh - Automated HTTPS setup using Caddy reverse proxy
#
# This script sets up HTTPS for planny-flows using Caddy, which automatically
# manages TLS certificates. Perfect for local development and Tailscale access.
#

set -euo pipefail

SCRIPT_NAME=$(basename "$0")
VERSION="1.0.0"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Disable colors if needed
if [[ -n "${NO_COLOR:-}" ]] || [[ "${TERM:-}" == "dumb" ]]; then
    RED="" GREEN="" YELLOW="" BLUE="" CYAN="" NC=""
fi

# Directories
PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
DEPLOY_DIR="${DEPLOY_DIR:-$HOME/.planny-flows}"
TEMPLATES_DIR="$PROJECT_DIR/deploy/templates"

# Default values
CLIENT_PORT=8193
API_PORT=3824
HTTPS_PORT=443
HTTP_PORT=80

# Tailscale detection
TAILSCALE_IP=""
TAILSCALE_HOSTNAME=""

function usage() {
    cat <<EOM

Set up HTTPS for planny-flows using Caddy reverse proxy.

usage: ${SCRIPT_NAME} [options]

options:
    --hostname <name>      Custom hostname (default: auto-detect from Tailscale or system)
    --tailscale            Force Tailscale mode (use Tailscale IP)
    --uninstall            Remove HTTPS configuration and stop Caddy
    -h|--help              Show this help message
    --version              Show version information

examples:
    ${SCRIPT_NAME}                    # Auto-detect best configuration
    ${SCRIPT_NAME} --tailscale        # Use Tailscale IP for HTTPS
    ${SCRIPT_NAME} --hostname myhost  # Use custom hostname
    ${SCRIPT_NAME} --uninstall        # Remove HTTPS setup

EOM
    exit 1
}

function log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

function log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

function log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

function log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

function check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check if deployment exists
    if [[ ! -d "$DEPLOY_DIR" ]]; then
        log_error "Deployment directory not found: $DEPLOY_DIR"
        log_error "Run ./deploy/setup.sh first"
        exit 1
    fi

    if [[ ! -f "$DEPLOY_DIR/start.sh" ]]; then
        log_error "start.sh not found in $DEPLOY_DIR"
        log_error "Run ./deploy/setup.sh first"
        exit 1
    fi

    log_success "Prerequisites OK"
}

function detect_tailscale() {
    log_info "Detecting Tailscale configuration..."

    # Check if Tailscale is installed
    if command -v tailscale &>/dev/null; then
        # Get Tailscale IP
        TAILSCALE_IP=$(tailscale ip -4 2>/dev/null || echo "")

        if [[ -n "$TAILSCALE_IP" ]]; then
            # Get Tailscale hostname
            TAILSCALE_HOSTNAME=$(tailscale status --json 2>/dev/null | grep -o '"HostName":"[^"]*"' | head -1 | cut -d'"' -f4 || hostname | sed 's/\.local$//')

            log_success "Tailscale detected!"
            echo -e "  ${CYAN}IP:${NC} $TAILSCALE_IP"
            echo -e "  ${CYAN}Hostname:${NC} $TAILSCALE_HOSTNAME"
            return 0
        fi
    fi

    log_info "Tailscale not detected or not configured"
    return 1
}

function install_caddy() {
    log_info "Installing Caddy..."

    if command -v caddy &>/dev/null; then
        local caddy_version
        caddy_version=$(caddy version 2>/dev/null | head -1 || echo "unknown")
        log_success "Caddy already installed: $caddy_version"
        return 0
    fi

    # Install via Homebrew
    if command -v brew &>/dev/null; then
        log_info "Installing Caddy via Homebrew..."
        brew install caddy || {
            log_error "Failed to install Caddy"
            exit 1
        }
        log_success "Caddy installed successfully"
    else
        log_error "Homebrew not found. Please install Homebrew or Caddy manually:"
        echo "  brew install caddy"
        echo "  # or visit: https://caddyserver.com/docs/install"
        exit 1
    fi
}

function generate_caddyfile() {
    local hostname="$1"
    local use_tailscale="${2:-false}"

    log_info "Generating Caddyfile..."

    local caddyfile_path="$DEPLOY_DIR/Caddyfile"

    if [[ "$use_tailscale" == "true" ]]; then
        # Tailscale configuration - use Tailscale IP with internal TLS
        cat > "$caddyfile_path" <<EOF
# Planny-Flows HTTPS Configuration (Tailscale)
# Auto-generated by setup-https.sh

{
    # Use local CA for internal/Tailscale certificates
    local_certs
    admin localhost:2019
}

# HTTPS on Tailscale IP
https://${TAILSCALE_IP} {
    tls internal

    # Client app
    handle /api/* {
        reverse_proxy localhost:${API_PORT}
    }

    # API proxy
    handle {
        reverse_proxy localhost:${CLIENT_PORT}
    }

    # Logging
    log {
        output file ${DEPLOY_DIR}/logs/caddy.log
        format console
    }
}

# Also listen on Tailscale hostname if available
https://${hostname}.ts.net {
    tls internal

    handle /api/* {
        reverse_proxy localhost:${API_PORT}
    }

    handle {
        reverse_proxy localhost:${CLIENT_PORT}
    }

    log {
        output file ${DEPLOY_DIR}/logs/caddy.log
        format console
    }
}

# HTTP redirect (optional, for local network access)
http://${hostname}.local {
    redir https://${TAILSCALE_IP} permanent
}
EOF
    else
        # Standard local configuration with self-signed certs
        cat > "$caddyfile_path" <<EOF
# Planny-Flows HTTPS Configuration
# Auto-generated by setup-https.sh

{
    local_certs
    admin localhost:2019
}

# Local HTTPS
https://${hostname}.local {
    tls internal

    # API endpoints
    handle /api/* {
        reverse_proxy localhost:${API_PORT}
    }

    # Client app
    handle {
        reverse_proxy localhost:${CLIENT_PORT}
    }

    # Logging
    log {
        output file ${DEPLOY_DIR}/logs/caddy.log
        format console
    }
}

# HTTP redirect
http://${hostname}.local {
    redir https://${hostname}.local{uri} permanent
}
EOF
    fi

    chmod 600 "$caddyfile_path"
    log_success "Created Caddyfile at $caddyfile_path"
}

function update_launchd_for_https() {
    log_info "Updating launchd configuration..."

    local plist_path="$DEPLOY_DIR/com.plannyflows-https.plist"
    
    # Determine Caddy path
    local caddy_path
    caddy_path=$(command -v caddy 2>/dev/null || echo "/opt/homebrew/bin/caddy")

    # Create a separate plist for Caddy
    cat > "$plist_path" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.plannyflows.https</string>
    <key>ProgramArguments</key>
    <array>
        <string>$caddy_path</string>
        <string>run</string>
        <string>--config</string>
        <string>${DEPLOY_DIR}/Caddyfile</string>
        <string>--adapter</string>
        <string>caddyfile</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${DEPLOY_DIR}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
        <key>Crashed</key>
        <true/>
    </dict>
    <key>StandardOutPath</key>
    <string>${DEPLOY_DIR}/logs/caddy-stdout.log</string>
    <key>StandardErrorPath</key>
    <string>${DEPLOY_DIR}/logs/caddy-error.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
    <key>ThrottleInterval</key>
    <integer>30</integer>
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
EOF

    log_success "Created HTTPS launchd plist"
}

function update_env_for_https() {
    log_info "Updating environment configuration for HTTPS..."

    local env_file="$DEPLOY_DIR/.env.production"
    local hostname="$1"
    local use_tailscale="${2:-false}"

    # Determine the client URL
    local client_url
    if [[ "$use_tailscale" == "true" ]]; then
        client_url="https://${TAILSCALE_IP}"
    else
        client_url="https://${hostname}.local"
    fi

    # Update CLIENT_URL if it exists
    if grep -q "^CLIENT_URL=" "$env_file" 2>/dev/null; then
        # macOS sed requires -i '' for in-place editing
        sed -i '' "s|^CLIENT_URL=.*|CLIENT_URL=${client_url}|" "$env_file"
    else
        echo "CLIENT_URL=${client_url}" >> "$env_file"
    fi

    log_success "Updated CLIENT_URL to ${client_url}"
}

function create_https_marker() {
    local hostname="$1"
    local use_tailscale="${2:-false}"

    cat > "$DEPLOY_DIR/.https-config" <<EOF
# HTTPS Configuration
HTTPS_ENABLED=true
HTTPS_MODE=${use_tailscale:+tailscale}${use_tailscale:-local}
HTTPS_HOSTNAME=${hostname}
TAILSCALE_IP=${TAILSCALE_IP}
TAILSCALE_HOSTNAME=${TAILSCALE_HOSTNAME}
CONFIGURED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF

    chmod 600 "$DEPLOY_DIR/.https-config"
}

function start_caddy() {
    log_info "Starting Caddy..."

    # Check if Caddy is already running
    if pgrep -f "caddy run" &>/dev/null; then
        log_info "Stopping existing Caddy process..."
        pkill -f "caddy run" 2>/dev/null || true
        sleep 1
    fi

    # Start Caddy
    cd "$DEPLOY_DIR" || exit 1

    # Run caddy validate first
    if ! caddy validate --config "$DEPLOY_DIR/Caddyfile" 2>/dev/null; then
        log_warning "Caddyfile validation had warnings, continuing..."
    fi

    # Start in background for now
    caddy run --config "$DEPLOY_DIR/Caddyfile" &
    local caddy_pid=$!

    sleep 2

    if kill -0 "$caddy_pid" 2>/dev/null; then
        log_success "Caddy started (PID: $caddy_pid)"
    else
        log_error "Caddy failed to start. Check logs at $DEPLOY_DIR/logs/"
        exit 1
    fi
}

function install_system_service() {
    log_info "Installing Caddy as system service..."

    local plist_source="$DEPLOY_DIR/com.plannyflows-https.plist"
    local plist_dest="/Library/LaunchDaemons/com.plannyflows-https.plist"

    if [[ ! -f "$plist_source" ]]; then
        log_error "HTTPS plist not found. Run setup first."
        exit 1
    fi

    echo ""
    echo -e "${YELLOW}This requires administrator privileges.${NC}"
    echo -e "Installing Caddy as a system service..."

    # Stop existing service if running
    sudo launchctl bootout system/com.plannyflows-https 2>/dev/null || true

    # Copy plist
    sudo cp "$plist_source" "$plist_dest" || {
        log_error "Failed to copy plist"
        exit 1
    }

    # Set proper permissions
    sudo chown root:wheel "$plist_dest"
    sudo chmod 644 "$plist_dest"

    # Load the service
    sudo launchctl bootstrap system "$plist_dest" || {
        log_error "Failed to load service"
        exit 1
    }

    log_success "Caddy service installed and started"
}

function uninstall_https() {
    log_info "Uninstalling HTTPS configuration..."

    # Stop Caddy service
    if sudo launchctl bootout system/com.plannyflows-https 2>/dev/null; then
        log_info "Stopped system Caddy service"
    fi

    # Stop any running Caddy processes
    if pgrep -f "caddy run" &>/dev/null; then
        pkill -f "caddy run" 2>/dev/null || true
        log_info "Stopped Caddy processes"
    fi

    # Remove plist
    if [[ -f "/Library/LaunchDaemons/com.plannyflows-https.plist" ]]; then
        sudo rm -f "/Library/LaunchDaemons/com.plannyflows-https.plist"
        log_info "Removed system plist"
    fi

    # Remove local files
    rm -f "$DEPLOY_DIR/Caddyfile"
    rm -f "$DEPLOY_DIR/com.plannyflows-https.plist"
    rm -f "$DEPLOY_DIR/.https-config"

    # Restore original CLIENT_URL in env
    local env_file="$DEPLOY_DIR/.env.production"
    local hostname
    hostname=$(hostname | sed 's/\.local$//')

    if [[ -f "$env_file" ]]; then
        sed -i '' "s|^CLIENT_URL=.*|CLIENT_URL=http://${hostname}.local:8193|" "$env_file"
        log_info "Restored HTTP CLIENT_URL"
    fi

    log_success "HTTPS configuration removed"
    echo ""
    echo -e "${GREEN}Your application is now accessible via HTTP only:${NC}"
    echo -e "  http://${hostname}.local:8193"
}

function display_success_message() {
    local hostname="$1"
    local use_tailscale="${2:-false}"

    echo ""
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}     HTTPS Setup Complete!${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
    echo ""

    if [[ "$use_tailscale" == "true" ]]; then
        echo -e "${CYAN}Access your application via Tailscale:${NC}"
        echo ""
        echo -e "  ${GREEN}From your phone (Tailscale connected):${NC}"
        echo -e "    ${YELLOW}https://${TAILSCALE_IP}${NC}"
        if [[ -n "$TAILSCALE_HOSTNAME" ]]; then
            echo -e "    ${YELLOW}https://${TAILSCALE_HOSTNAME}.ts.net${NC}"
        fi
        echo ""
        echo -e "  ${BLUE}Note:${NC} You may see a certificate warning."
        echo -e "  This is normal for self-signed certificates on local networks."
        echo -e "  Click 'Advanced' -> 'Proceed to site' to continue."
    else
        echo -e "${CYAN}Access your application:${NC}"
        echo ""
        echo -e "  ${YELLOW}https://${hostname}.local${NC}"
        echo ""
        echo -e "  ${BLUE}Note:${NC} You may see a certificate warning."
        echo -e "  This is normal for self-signed certificates."
        echo -e "  Click 'Advanced' -> 'Proceed to site' to continue."
    fi

    echo ""
    echo -e "${BLUE}Configuration files:${NC}"
    echo -e "  Caddyfile:   $DEPLOY_DIR/Caddyfile"
    echo -e "  HTTPS config: $DEPLOY_DIR/.https-config"
    echo ""
    echo -e "${BLUE}To install as a system service (starts on boot):${NC}"
    echo -e "  ${YELLOW}./deploy/scripts/setup-https.sh --install-service${NC}"
    echo ""
    echo -e "${BLUE}Useful commands:${NC}"
    echo -e "  Status:     caddy validate --config $DEPLOY_DIR/Caddyfile"
    echo -e "  Logs:       tail -f $DEPLOY_DIR/logs/caddy.log"
    echo -e "  Reload:     caddy reload --config $DEPLOY_DIR/Caddyfile"
    echo -e "  Uninstall:  ./deploy/scripts/setup-https.sh --uninstall"
    echo ""
}

function main() {
    local hostname=""
    local use_tailscale=false
    local do_uninstall=false
    local install_service=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
        --hostname)
            shift
            hostname="$1"
            ;;
        --tailscale)
            use_tailscale=true
            ;;
        --uninstall)
            do_uninstall=true
            ;;
        --install-service)
            install_service=true
            ;;
        --version)
            echo "${SCRIPT_NAME} version ${VERSION}"
            exit 0
            ;;
        -h | --help)
            usage
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            ;;
        esac
        shift
    done

    # Handle uninstall
    if [[ "$do_uninstall" == true ]]; then
        uninstall_https
        exit 0
    fi

    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}     Planny-Flows HTTPS Setup${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo ""

    # Check prerequisites
    check_prerequisites

    # Detect or use provided hostname
    if [[ -z "$hostname" ]]; then
        hostname=$(hostname | sed 's/\.local$//')
    fi

    # Auto-detect Tailscale if not explicitly set
    if [[ "$use_tailscale" == false ]]; then
        if detect_tailscale; then
            echo ""
            echo -e "${CYAN}Tailscale detected! Would you like to use Tailscale for HTTPS?${NC}"
            echo -e "This will configure HTTPS using your Tailscale IP address."
            echo ""
            read -r -p "Use Tailscale? [y/N] " response
            case "$response" in
            [yY][eE][sS] | [yY])
                use_tailscale=true
                ;;
            esac
        fi
    else
        # Force Tailscale detection
        detect_tailscale || {
            log_error "Tailscale requested but not available"
            exit 1
        }
    fi

    # Install Caddy
    install_caddy

    # Generate configuration
    generate_caddyfile "$hostname" "$use_tailscale"

    # Update environment
    update_env_for_https "$hostname" "$use_tailscale"

    # Create HTTPS marker
    create_https_marker "$hostname" "$use_tailscale"

    # Update launchd
    update_launchd_for_https

    # Start Caddy
    start_caddy

    # Install system service if requested
    if [[ "$install_service" == true ]]; then
        install_system_service
    fi

    # Show success message
    display_success_message "$hostname" "$use_tailscale"
}

# Run main
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
    exit 0
fi
