export const loanCopy = {
  title: 'Préstamos',
  dashboard: 'Dashboard',
  loans: 'Préstamos',
  borrowers: 'Personas',
  newLoan: 'Nuevo Préstamo',
  receipt: 'Generar Recibo',
};

export const loanNavigation = [
  { key: 'dashboard', label: loanCopy.dashboard },
  { key: 'loans', label: loanCopy.loans },
  { key: 'borrowers', label: loanCopy.borrowers },
  { key: 'new-loan', label: loanCopy.newLoan },
  { key: 'receipt', label: loanCopy.receipt },
];

export const borrowerCopy = {
  title: 'Personas',
  search: 'Buscá por nombre o apellido',
  add: 'Agregar persona',
  empty: 'Todavía no hay personas cargadas.',
  noMatches: 'No encontramos coincidencias.',
  firstName: 'Nombre',
  lastName: 'Apellido',
  email: 'Email',
  phone: 'Teléfono',
  address: 'Domicilio',
  nationalId: 'DNI / documento',
  notes: 'Notas',
  loanCount: 'Préstamos',
};

export const loanFormCopy = {
  createTitle: 'Nuevo Préstamo',
  editTitle: 'Editar Préstamo',
  picker: 'Persona',
  amount: 'Monto',
  currency: 'Moneda',
  date: 'Fecha',
  concept: 'Concepto',
  lender: 'Prestamista',
  city: 'Ciudad',
  advancePaid: 'Pago adelantado',
  installmentAmount: 'Valor de la cuota',
  installmentOptional: 'Opcional',
  balancePreview: 'Saldo pendiente',
  save: 'Guardar préstamo',
  saveChanges: 'Guardar cambios',
  saving: 'Guardando…',
  loading: 'Cargando préstamo…',
  loadError: 'No pudimos cargar el préstamo. Intentá de nuevo.',
  retry: 'Reintentar',
  created: 'Préstamo registrado.',
  updated: 'Préstamo actualizado.',
  removed: 'Préstamo eliminado.',
  emptyPicker: 'Elegí una persona para continuar.',
};

export const loansListCopy = {
  title: 'Préstamos',
  empty: 'Todavía no hay préstamos. Cargá el primero.',
  loading: 'Cargando préstamos…',
  loadError: 'No pudimos cargar los préstamos. Intentá de nuevo.',
  retry: 'Reintentar',
  edit: 'Editar',
  remove: 'Eliminar',
  removeTitle: '¿Eliminar préstamo?',
  removeMessage: 'Se elimina el préstamo. No se puede deshacer.',
  borrower: 'Persona',
  balance: 'Saldo pendiente',
  installment: 'Cuota',
  concept: 'Concepto',
  lender: 'Prestamista',
  city: 'Ciudad',
};
